
package pe.egcc.demows.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibrosWs", targetNamespace = "http://ws.demows.egcc.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibrosWs {


    /**
     * 
     * @return
     *     returns java.util.List<pe.egcc.demows.ws.Libro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "traerLibros", targetNamespace = "http://ws.demows.egcc.pe/", className = "pe.egcc.demows.ws.TraerLibros")
    @ResponseWrapper(localName = "traerLibrosResponse", targetNamespace = "http://ws.demows.egcc.pe/", className = "pe.egcc.demows.ws.TraerLibrosResponse")
    @Action(input = "http://ws.demows.egcc.pe/LibrosWs/traerLibrosRequest", output = "http://ws.demows.egcc.pe/LibrosWs/traerLibrosResponse")
    public List<Libro> traerLibros();

}
