
package pe.egcc.demows.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibrosWsService", targetNamespace = "http://ws.demows.egcc.pe/", wsdlLocation = "http://localhost:8087/librosws?wsdl")
public class LibrosWsService
    extends Service
{

    private final static URL LIBROSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBROSWSSERVICE_EXCEPTION;
    private final static QName LIBROSWSSERVICE_QNAME = new QName("http://ws.demows.egcc.pe/", "LibrosWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8087/librosws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBROSWSSERVICE_WSDL_LOCATION = url;
        LIBROSWSSERVICE_EXCEPTION = e;
    }

    public LibrosWsService() {
        super(__getWsdlLocation(), LIBROSWSSERVICE_QNAME);
    }

    public LibrosWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBROSWSSERVICE_QNAME, features);
    }

    public LibrosWsService(URL wsdlLocation) {
        super(wsdlLocation, LIBROSWSSERVICE_QNAME);
    }

    public LibrosWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBROSWSSERVICE_QNAME, features);
    }

    public LibrosWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibrosWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LibrosWs
     */
    @WebEndpoint(name = "LibrosWsPort")
    public LibrosWs getLibrosWsPort() {
        return super.getPort(new QName("http://ws.demows.egcc.pe/", "LibrosWsPort"), LibrosWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibrosWs
     */
    @WebEndpoint(name = "LibrosWsPort")
    public LibrosWs getLibrosWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.demows.egcc.pe/", "LibrosWsPort"), LibrosWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBROSWSSERVICE_EXCEPTION!= null) {
            throw LIBROSWSSERVICE_EXCEPTION;
        }
        return LIBROSWSSERVICE_WSDL_LOCATION;
    }

}
